# Stage 1: Build
FROM node:20 AS builder
WORKDIR /app

COPY package.json yarn.lock turbo.json ./
COPY apps/backend/package.json ./apps/backend/
COPY packages/core/package.json ./packages/core/

RUN yarn config set registry https://registry.npmmirror.com
RUN yarn install --network-timeout 600000

COPY apps ./apps
COPY packages ./packages

# ✅ Gera Prisma Client no build
WORKDIR /app/apps/backend
ENV DATABASE_URL=postgresql://dummy-url
RUN yarn prisma:generate

RUN yarn build

# Stage 2: Production
FROM node:20 AS production
WORKDIR /app

ENV NODE_ENV=production

COPY package.json yarn.lock ./
COPY apps/backend/package.json ./apps/backend/
COPY packages/core/package.json ./packages/core/

RUN yarn config set registry https://registry.npmmirror.com
RUN yarn install --production --network-timeout 600000

COPY --from=builder /app/apps/backend/dist ./apps/backend/dist
COPY --from=builder /app/apps/backend/prisma ./apps/backend/prisma
COPY --from=builder /app/packages ./packages

# ✅ Copia Prisma Client já gerado
COPY --from=builder /app/apps/backend/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/apps/backend/node_modules/@prisma ./node_modules/@prisma

EXPOSE 4000

# 🧼 Agora você pode executar direto a aplicação sem prisma:generate
CMD ["node", "apps/backend/dist/main.js"]
